services:
  - type: web
    name: nrs-software
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn nrs_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nrs-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*" # Update this with your actual domain later

databases:
  - name: nrs-db
    plan: free
