# Generated by Django 6.0.4 on 2026-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ACCOUNTANT', 'Accountant'), ('SUPPLIER', 'Supplier'), ('OWNER', 'Owner'), ('BUYER', 'Buyer')], default='BUYER', max_length=20),
        ),
    ]
