# Generated by Django 6.0.4 on 2026-04-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='p_approve_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_create_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_delete_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_edit_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_manage_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_manage_contacts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_manage_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_manage_requisitions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_manage_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_manage_visual_requisitions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_price_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_view_audit_logs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_view_bill_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_view_bills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='p_view_gate_entry',
            field=models.BooleanField(default=False),
        ),
    ]
