# Generated by Django 6.0.4 on 2026-04-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_p_approve_bill_user_p_create_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid_number',
            field=models.CharField(blank=True, help_text='National ID Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_manage_authorizations',
            field=models.BooleanField(default=False),
        ),
    ]
