# Generated by Django 5.2.5 on 2026-04-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_nid_number_user_p_manage_authorizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_drive_json_key',
            field=models.TextField(blank=True, help_text='Google Drive Service Account JSON Key', null=True),
        ),
    ]
