# Generated by Django 5.2.5 on 2026-04-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_p_manage_peer_transactions_peertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='peertransaction',
            name='receiver_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peertransaction',
            name='sender_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
