# Generated by Django 5.2.5 on 2026-04-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_peertransaction_receiver_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='p_print_documents',
            field=models.BooleanField(default=False),
        ),
    ]
