# Generated by Django 5.2.5 on 2026-04-11 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PRICED', 'Priced'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('supplier_bin', models.CharField(blank=True, max_length=100)),
                ('supplier_address', models.TextField(blank=True)),
                ('supplier_contact', models.CharField(blank=True, max_length=100)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('buyer_bin', models.CharField(blank=True, max_length=100)),
                ('buyer_address', models.TextField(blank=True)),
                ('buyer_contact', models.CharField(blank=True, max_length=100)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('duty_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('challan_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('display_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.transaction')),
            ],
        ),
    ]
