# Generated by Django 5.2.5 on 2026-04-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('BUYER', 'Buyer')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('bin_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
