# Generated by Django 5.2.5 on 2026-04-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_transactioncategory_alter_transaction_challan_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='display_price',
            new_name='base_price',
        ),
    ]
