# Generated by Django 5.2.5 on 2026-04-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_rename_display_price_transactionitem_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='default_duty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='default_profit_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='default_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='default_vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
