# Generated by Django 5.2.5 on 2026-04-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_transactioncategory_default_duty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='invoice_prefix',
            field=models.CharField(default='INV', max_length=10),
        ),
    ]
