# Generated by Django 5.2.5 on 2026-04-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_transactioncategory_invoice_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionitem',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
