# Generated by Django 5.2.5 on 2026-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_transactionitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service_charge_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='default_service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
