# Generated by Django 5.2.5 on 2026-04-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_transaction_service_charge_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='unit',
            field=models.CharField(default='Pcs', max_length=50),
        ),
    ]
