# Generated by Django 5.2.5 on 2026-04-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_transactionitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='color_theme',
            field=models.CharField(choices=[('gray', 'Gray (Default)'), ('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('indigo', 'Indigo'), ('pink', 'Pink'), ('orange', 'Orange'), ('teal', 'Teal')], default='gray', max_length=20),
        ),
    ]
