# Generated by Django 5.2.5 on 2026-04-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_transactioncategory_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PRICED', 'Priced'), ('APPROVED', 'Approved'), ('SUBMITTED', 'Submitted'), ('RELEASED', 'Released')], default='DRAFT', max_length=20),
        ),
    ]
