# Generated by Django 5.2.5 on 2026-04-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_add_status_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
