# Generated by Django 6.0.4 on 2026-04-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_market_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='market_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
