# Generated by Django 6.0.4 on 2026-04-15 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_transaction_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='default_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def_categories_buyer', to='documents.businessparty'),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def_categories_supplier', to='documents.businessparty'),
        ),
    ]
