# Generated by Django 5.2.5 on 2026-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_transactioncategory_default_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessparty',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='e.g. 88017...', max_length=20),
        ),
    ]
