# Generated by Django 6.0.4 on 2026-04-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_businessparty_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_market_sync',
        ),
        migrations.RemoveField(
            model_name='product',
            name='market_price',
        ),
        migrations.AddField(
            model_name='product',
            name='upscale_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
