# Generated by Django 6.0.4 on 2026-04-16 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_visualrequisition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('issuer_name', models.CharField(max_length=255)),
                ('issuer_address', models.TextField()),
                ('trading_name', models.CharField(default='NRS Software', max_length=255)),
                ('nominee_nid', models.CharField(max_length=50)),
                ('check_number', models.CharField(max_length=100)),
                ('check_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_authorizations', to=settings.AUTH_USER_MODEL)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
