# Generated by Django 5.2.5 on 2026-04-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_checkauthorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkauthorization',
            name='check_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='checkauthorization',
            name='check_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkauthorization',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkauthorization',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
