# Generated by Django 5.2.5 on 2026-04-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_product_added_by_product_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='unit_price_uplifted',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Owner set price before taxes. If blank, global profit margin applies.', max_digits=10, null=True),
        ),
    ]
