# Generated by Django 5.2.5 on 2026-04-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_transactionitem_unit_price_uplifted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='upscale_value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='base_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='unit_price_uplifted',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Owner set price before taxes. If blank, global profit margin applies.', max_digits=10, null=True),
        ),
    ]
