# Generated by Django 5.2.5 on 2026-06-10 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_businessparty_is_deleted_businessparty_is_dirty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='secondary_category',
            field=models.ForeignKey(blank=True, help_text='Optional secondary category for dual-category registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_transactions', to='documents.transactioncategory'),
        ),
    ]
