# Generated by Django 5.2.5 on 2026-06-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_transaction_secondary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='secondary_duty_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='secondary_profit_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='secondary_service_charge_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='secondary_tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='secondary_vat_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='is_secondary',
            field=models.BooleanField(default=False),
        ),
    ]
