# Generated by Django 6.0.4 on 2026-06-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_transaction_secondary_duty_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
