# Generated by Django 5.2.5 on 2026-07-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_transactionitem_checkout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessparty',
            name='seal_image',
            field=models.ImageField(blank=True, null=True, upload_to='seals/'),
        ),
        migrations.AddField(
            model_name='businessparty',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
