# Generated by Django 5.2.5 on 2026-07-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_businessparty_seal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessparty',
            name='ceo_name',
            field=models.CharField(blank=True, help_text='Name of the person in charge / CEO', max_length=255),
        ),
    ]
