# Generated by Django 5.2.5 on 2026-07-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_businessparty_ceo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_daily_basis',
            field=models.BooleanField(default=False, help_text='Toggles daily basis mode for room service / hotel stay bills.'),
        ),
    ]
