# Generated by Django 5.2.5 on 2026-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_transaction_is_daily_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='decimal_display_mode',
            field=models.CharField(choices=[('DEFAULT', 'Show Decimals'), ('ROUND_UP', 'Round Up'), ('TRUNCATE', 'Truncate'), ('ROUND', 'Round Nearest')], default='DEFAULT', max_length=20),
        ),
    ]
