# Generated by Django 5.2.5 on 2026-07-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_transactionsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Flat discount amount deducted from the grand total', max_digits=12),
        ),
    ]
