# Generated by Django 5.2.5 on 2026-07-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_transaction_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage deducted from the grand total', max_digits=5),
        ),
    ]
