# Generated by Django 5.2.5 on 2026-07-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_remove_transaction_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='calculation_mode',
            field=models.CharField(choices=[('forward', 'Forward'), ('reverse', 'Reverse')], default='forward', max_length=20),
        ),
    ]
