# Generated by Django 5.2.5 on 2026-07-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_transaction_calculation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discount_flat',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Flat discount amount (Tk) deducted in addition to the percentage discount', max_digits=12),
        ),
    ]
