# Generated by Django 5.2.5 on 2026-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_transaction_discount_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
    ]
