# Generated by Django 5.2.5 on 2026-07-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0040_alter_transactionitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='override_duty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Item-specific Duty %; leave blank to use the bill's rate", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='override_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Item-specific TAX %; leave blank to use the bill's rate", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='override_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Item-specific VAT %; leave blank to use the bill's rate", max_digits=5, null=True),
        ),
    ]
