# Generated by Django 5.2.5 on 2026-07-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0041_transactionitem_override_duty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessparty',
            name='color_theme',
            field=models.CharField(choices=[('blue', 'Blue'), ('claude', 'Claude (Clay)'), ('crimson', 'Crimson')], default='blue', help_text="Colour theme used on this supplier's printed invoices/quotations", max_length=20),
        ),
        migrations.AddField(
            model_name='businessparty',
            name='designation',
            field=models.CharField(blank=True, help_text="Signatory's designation, e.g. Proprietor & CEO", max_length=120),
        ),
    ]
