# Generated by Django 5.2.5 on 2026-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0044_printlayout_per_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessparty',
            name='print_layout',
            field=models.CharField(choices=[('classic', 'Classic — brand sidebar'), ('letterhead', 'Letterhead — centred masthead'), ('industrial', 'Industrial — bold header band')], default='classic', help_text="Page design used on this supplier's printed invoices/quotations", max_length=20),
        ),
    ]
