# Generated by Django 5.2.5 on 2026-04-11 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('documents', '0005_rename_display_price_transactionitem_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.transaction'),
        ),
    ]
